### ISSUE TITLE
Help for Impulse modification

### ISSUE THREAD

**Issue by AlphaBril** [peace-maker/smrpg#268] opened 2018-01-31 16:38 UTC
Hello guys, I'm working on a knife server, and I was wondering if it's possible to change the activation of impulse, short example : 
-Normal Impulse : Player A get a movement speed bonus because Player B inflicted damage to Player A
-Modified Impulse : Player A get a movement speed bonus because he used his left click

I don't really know in what part of the smrpg_upgrade_impulse.sp I have to act, I guess it's about line 156 to 242.

Thanks for the help in coming, and have a good day.

AlphaBril

**Comment by peace-maker** [comment] 2018-01-31 16:53
This seems like a duplicate of #213 and #178 just applying the effect whenever someone shoots their weapon. I never understood the point of it, but looks like it's a freqently requested feature.
I'll add that adrenaline upgrade with an option to not require the player to hit someone when using the weapon.

**Comment by AlphaBril** [comment] 2018-02-01 15:48
I know this isn't something to ask, but in the current case we already launched the server and we build it on a day to day basis, even if this upgrade is the most important part of it. So I was wondering if you can give a time range for this release ?

**Comment by Nobody-x** [comment] 2018-02-01 16:01
I already have this upgrade, I'll try to make a >PR later in the day.

**Comment by AlphaBril** [comment] 2018-02-17 18:24
hello Nobody, that would be awesome ! :D I'll look forward to that ty a lot.

**Comment by AlphaBril** [comment] 2018-02-27 17:10
Hello guys, I'm back again on this topic.. it's been 27 days since I opened it, I just want to remenber you that I opened it not as an "upgrade idea" but in need of help to add a modification on the impulse plugin. I know you work when you want and you have better to do than listen to an ignorant like me, but please if you can't tell me when the "adrenaline" maj will be PR, tell me just the one little line to change in the impulse plugin and with what i should change her...

**Comment by Nobody-x** [comment] 2018-02-27 20:38
Hello @AlphaBril,

I'm really sorry, I was busy on an other project and forget about this issue, I'm preparing this PR right now.
Thank you for remind me about that :)

**Comment by AlphaBril** [comment] 2018-02-27 20:59
No, thank YOU for doing this for the community :)

**Closed** 2018-02-28 13:40 UTC
Labels: upgrade idea
