### ISSUE TITLE
bug with invisibility

### ISSUE THREAD

**Issue by Septembers** [peace-maker/smrpg#362] opened 2021-01-13 13:24 UTC
On some maps such bugs occur when you level up the invisibility ability.
Is this really something to fix, or is it a map problem?

https://youtu.be/K-JpKJOQaY0

**Comment by peace-maker** [comment] 2021-01-13 14:08
This appears to be a duplicate of #354? Please keep it in one single issue instead of creating a new one.

**Closed by peace-maker** 2021-01-13 14:08 UTC
