### ISSUE TITLE
[BUG] Upgrade clipsize + Shotgun

### ISSUE THREAD

**Issue by baferpro** [peace-maker/smrpg#288] opened 2018-08-10 11:30 UTC
When start reload weapon then breaks down anim ( endless reload ) and ammunition are not replenished. Only if you shoot. Can be fixed?

**Comment by peace-maker** [comment] 2018-08-14 09:30
This is a duplicate of #121. It's just tedious to reverse engineer the shotgun reloading code and I haven't got around to it yet. I'll bump it up.

**Closed by peace-maker** 2018-08-14 09:30 UTC

**Comment by baferpro** [comment] 2018-08-14 18:04
Okay, thx.
