### ISSUE TITLE
Someone know how to fix that ?

### ISSUE THREAD

**Issue by Nobody-x** [peace-maker/smrpg#244] opened 2017-01-06 14:36 UTC
I'm running Sourcemod 1.8 stable and this is my error log :

```
L 01/06/2017 - 00:02:11: SourceMod error session started
L 01/06/2017 - 00:02:11: Info (map "bw_noname_hiver2016_v3") (file "errors_20170106.log")
L 01/06/2017 - 00:02:11: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 00:02:11: [SM] Blaming: smrpg.smx
L 01/06/2017 - 00:02:11: [SM] Call stack trace:
L 01/06/2017 - 00:02:11: [SM]   [0] Call_Finish
L 01/06/2017 - 00:02:11: [SM]   [1] Line 338, smrpg/smrpg_players.sp::ResetStats
L 01/06/2017 - 00:02:11: [SM]   [2] Line 348, smrpg/smrpg_players.sp::RemovePlayer
L 01/06/2017 - 00:02:11: [SM]   [3] Line 438, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientDisconnect
L 01/06/2017 - 00:46:30: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 00:46:30: [SM] Blaming: smrpg.smx
L 01/06/2017 - 00:46:30: [SM] Call stack trace:
L 01/06/2017 - 00:46:30: [SM]   [0] Call_Finish
L 01/06/2017 - 00:46:30: [SM]   [1] Line 338, smrpg/smrpg_players.sp::ResetStats
L 01/06/2017 - 00:46:30: [SM]   [2] Line 348, smrpg/smrpg_players.sp::RemovePlayer
L 01/06/2017 - 00:46:30: [SM]   [3] Line 438, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientDisconnect
L 01/06/2017 - 00:47:16: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 00:47:16: [SM] Blaming: smrpg.smx
L 01/06/2017 - 00:47:16: [SM] Call stack trace:
L 01/06/2017 - 00:47:16: [SM]   [0] Call_Finish
L 01/06/2017 - 00:47:16: [SM]   [1] Line 378, smrpg/smrpg_players.sp::NotifyUpgradePluginsOfLevel
L 01/06/2017 - 00:47:16: [SM]   [2] Line 414, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientPutInServer
L 01/06/2017 - 00:55:21: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 00:55:21: [SM] Blaming: smrpg.smx
L 01/06/2017 - 00:55:21: [SM] Call stack trace:
L 01/06/2017 - 00:55:21: [SM]   [0] Call_Finish
L 01/06/2017 - 00:55:21: [SM]   [1] Line 338, smrpg/smrpg_players.sp::ResetStats
L 01/06/2017 - 00:55:21: [SM]   [2] Line 348, smrpg/smrpg_players.sp::RemovePlayer
L 01/06/2017 - 00:55:21: [SM]   [3] Line 438, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientDisconnect
L 01/06/2017 - 00:55:41: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 00:55:41: [SM] Blaming: smrpg.smx
L 01/06/2017 - 00:55:41: [SM] Call stack trace:
L 01/06/2017 - 00:55:41: [SM]   [0] Call_Finish
L 01/06/2017 - 00:55:41: [SM]   [1] Line 338, smrpg/smrpg_players.sp::ResetStats
L 01/06/2017 - 00:55:41: [SM]   [2] Line 348, smrpg/smrpg_players.sp::RemovePlayer
L 01/06/2017 - 00:55:41: [SM]   [3] Line 438, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientDisconnect
L 01/06/2017 - 01:01:48: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 01:01:48: [SM] Blaming: smrpg.smx
L 01/06/2017 - 01:01:48: [SM] Call stack trace:
L 01/06/2017 - 01:01:48: [SM]   [0] Call_Finish
L 01/06/2017 - 01:01:48: [SM]   [1] Line 338, smrpg/smrpg_players.sp::ResetStats
L 01/06/2017 - 01:01:48: [SM]   [2] Line 348, smrpg/smrpg_players.sp::RemovePlayer
L 01/06/2017 - 01:01:48: [SM]   [3] Line 438, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientDisconnect
L 01/06/2017 - 01:02:48: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 01:02:48: [SM] Blaming: smrpg.smx
L 01/06/2017 - 01:02:48: [SM] Call stack trace:
L 01/06/2017 - 01:02:48: [SM]   [0] Call_Finish
L 01/06/2017 - 01:02:48: [SM]   [1] Line 378, smrpg/smrpg_players.sp::NotifyUpgradePluginsOfLevel
L 01/06/2017 - 01:02:48: [SM]   [2] Line 414, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientPutInServer
L 01/06/2017 - 01:07:02: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 01:07:02: [SM] Blaming: smrpg.smx
L 01/06/2017 - 01:07:02: [SM] Call stack trace:
L 01/06/2017 - 01:07:02: [SM]   [0] Call_Finish
L 01/06/2017 - 01:07:02: [SM]   [1] Line 338, smrpg/smrpg_players.sp::ResetStats
L 01/06/2017 - 01:07:02: [SM]   [2] Line 348, smrpg/smrpg_players.sp::RemovePlayer
L 01/06/2017 - 01:07:02: [SM]   [3] Line 438, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientDisconnect
L 01/06/2017 - 01:09:56: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 01:09:56: [SM] Blaming: smrpg.smx
L 01/06/2017 - 01:09:56: [SM] Call stack trace:
L 01/06/2017 - 01:09:56: [SM]   [0] Call_Finish
L 01/06/2017 - 01:09:56: [SM]   [1] Line 338, smrpg/smrpg_players.sp::ResetStats
L 01/06/2017 - 01:09:56: [SM]   [2] Line 348, smrpg/smrpg_players.sp::RemovePlayer
L 01/06/2017 - 01:09:56: [SM]   [3] Line 438, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientDisconnect
L 01/06/2017 - 01:13:27: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 01:13:27: [SM] Blaming: smrpg.smx
L 01/06/2017 - 01:13:27: [SM] Call stack trace:
L 01/06/2017 - 01:13:27: [SM]   [0] Call_Finish
L 01/06/2017 - 01:13:27: [SM]   [1] Line 338, smrpg/smrpg_players.sp::ResetStats
L 01/06/2017 - 01:13:27: [SM]   [2] Line 348, smrpg/smrpg_players.sp::RemovePlayer
L 01/06/2017 - 01:13:27: [SM]   [3] Line 438, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientDisconnect
L 01/06/2017 - 01:16:45: [SM] Exception reported: Plugin not runnable
L 01/06/2017 - 01:16:45: [SM] Blaming: smrpg.smx
L 01/06/2017 - 01:16:45: [SM] Call stack trace:
L 01/06/2017 - 01:16:45: [SM]   [0] Call_Finish
L 01/06/2017 - 01:16:45: [SM]   [1] Line 378, smrpg/smrpg_players.sp::NotifyUpgradePluginsOfLevel
L 01/06/2017 - 01:16:45: [SM]   [2] Line 414, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnClientPutInServer

L 01/06/2017 - 06:07:01: SourceMod error session started
L 01/06/2017 - 06:07:01: Info (map "bw_noname_hiver2016_v3") (file "errors_20170106.log")
L 01/06/2017 - 06:07:01: [SM] Exception reported: Script execution timed out
L 01/06/2017 - 06:07:01: [SM] Blaming: smrpg.smx
L 01/06/2017 - 06:07:01: [SM] Call stack trace:
L 01/06/2017 - 06:07:01: [SM]   [1] Line 277, F:\___Servers\__addons\smrpg_nn\scripting\smrpg.sp::OnPluginStart
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg.smx": Error detected in plugin startup (see error logs)
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "serverredirect_cmds.smx": Could not find required plugin "serverredir"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_health.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_vampire.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_ljump_noname.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_keyhint_info.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_cstrike.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_firepistol.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_armorregen_cstrike.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_stealth.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_adrenaline.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_commandlist.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_resetstats.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_icestab.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_fpistol.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_speed.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_bouncybullets.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_resup.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_regen.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_chatxpstats.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_mirrordamage_noname.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Unable to load plugin "smrpg_upgrade_gravity.smx": Could not find required plugin "smrpg"
L 01/06/2017 - 06:07:01: [SM] Exception reported: Not enough space on the heap
L 01/06/2017 - 06:07:01: [STEAMTOOLS] Server Gameplay Stats received with an unexpected eResult. (eResult = 2)
L 01/06/2017 - 06:07:01: [STEAMTOOLS] Server Gameplay Stats received with an unexpected eResult. (eResult = 20)

```

The first lines spamming the logs (when someone disconnecting).
The last part of the lines (after the reboot at 6am) is a bug that happens every two or three days and prevents the RPG from working.

Apparently there is nothing we can do for fix that...

**Comment by peace-maker** [comment] 2017-01-07 03:12
Is one of your upgrades failing after starting up correctly first? Could you paste the output of `sm exts list` please?

Is line 277 in your smrpg.sp the same as in [master](https://github.com/peace-maker/smrpg/blob/master/scripting/smrpg.sp#L277)? You're running some modifications right? Might be hard to help here :(

**Comment by Nobody-x** [comment] 2017-01-07 17:37
Here the `sm exts list` command : 
```
sm exts list
[SM] Displaying 20 extensions:
[01] Automatic Updater (1.8.0.5964): Updates SourceMod gamedata files
[02] Webternet (1.8.0.5964): Extension for interacting with URLs
[03] SMJansson (2.3.1/3): JSON parser/writer
[04] CS Tools (1.8.0.5964): CS extended functionality
[05] BinTools (1.8.0.5964): Low-level C/C++ Calling API
[06] SDK Tools (1.8.0.5964): Source SDK Tools
[07] Regex (1.8.0.5964): Provides regex natives for plugins
[08] SDK Hooks (1.8.0.5964): Source SDK Hooks
[09] Top Menus (1.8.0.5964): Creates sorted nested menus
[10] Client Preferences (1.8.0.5964): Saves client preference settings
[11] SQLite (1.8.0.5964): SQLite Driver
[12] GeoIP (1.8.0.5964): Geographical IP information
[13] GeoIPCity (1.1.2): Geographical IP information
[14] SteamTools (0.8.3): SteamWorks for SourceMod.
[15] SteamWorks Extension (1.2): Exposes SteamWorks functions to Developers
[16] cURL Extension (1.3.0.0): cURL Extension
[17] Socket (3.0.1): Socket extension for SourceMod
[18] MessageBot (2.0): MessageBot Extension
[19] DHooks (2.1.1): Dynamic Hooks
[20] MySQL-DBI (1.8.0.5964): MySQL driver implementation for DBI
```

All modifications I've done to the smrpg core are databases one. I can't access to my modifications before tomorow.

Oh and just seen an error with `sm plugins list` command
```
smrpg_upgrade_damage_noname.smx (SM:RPG Upgrade > Damage+): Can't read config file in configs/smrpg/damage_weapons.cfg!
```

I'll check that but i don't think it's the cause of crashes. I edited a little bit this upgrade and it seems to work properly on the server.

**Comment by Stefanoss** [comment] 2017-01-08 00:40
It is fixed :) Thank you and awesome mod <3

2017-01-07 17:37 GMT+00:00 Nobody-x <notifications@github.com>:

**Comment by peace-maker** [comment] 2017-01-08 02:24
The first errors should be because of that damage upgrade failing after it registered itself as an upgrade. That's fixed now indeed.

Everytime I've seen the other kind of error `Not enough space on the heap`, it's been because of some other external issue with some extension. Most commonly because it tried to call sourcepawn functions from a different thread. That fucked up the VM causing it to error out eventually.

I'm not sure about the timeout. I don't see where it could spend too much time..

**Comment by Nobody-x** [comment] 2017-01-08 10:12
Ok thanks, I'll try to correct that first. 

For the timeout, there is only one server where it's happen. I'll make more tests on multiple server. Maybe another plugin, or extension.

**Comment by peace-maker** [comment] 2017-01-12 00:12
I'll close this one, since it's not reproducible and most likely caused by some other external factor.

**Closed by peace-maker** 2017-01-12 00:12 UTC
