### ISSUE TITLE
CS:GO entity 'weapon_knife' not working

### ISSUE THREAD

**Issue by aqqw1** [peace-maker/smrpg#228] opened 2016-10-18 11:50 UTC
Hi!
Trying to make knife more powerful in CS:GO in damage_weapons.cfg & weapon_experience.cfg with:
"DamagePlusWeapons"
{
//  "weapon_deagle"
//  {
//      "dmg_increase" "0.05"
//      "max_additional_dmg" "35"
//  }
    "weapon_knife"
    {
        "dmg_increase" "0.1"
        "max_additional_dmg" "250"
    }
}

and

"SMRPGWeaponExperience"
{
    "weapon_hegrenade"
    {
        "exp_damage" "8.0"
        "exp_kill" "12.0"
    }
    "weapon_ssg08"
    {
        "exp_damage" "8.0"
        "exp_kill" "10.0"
    }
    "weapon_knife"
    {
        "exp_damage" "8.0"
        "exp_kill" "12.0"
    }
}

But there seems to be no effect for knife. XP Rate for ssg08, hegrenade is working well.

Already tried to replace 'weapon_knife' with 'knife' but nothing has changed. It seems that the entity for knife is not affected. Any ideas?

Thank you for your great work with this mod!!! Real Fun!

**Comment by peace-maker** [comment] 2016-10-19 03:04
Hm, have you tried adding the entity names for the different kind of knives? maybe you're not using the default one? like `weapon_knifegg` or `weapon_knife_butterfly`

**Comment by aqqw1** [comment] 2016-10-19 09:46
I tried it without success. I also use the default knife. mhhh

**Comment by peace-maker** [comment] 2018-02-28 15:36
I just tested this and it's working fine for me? No special case for the knife.
Closing this for now since I can't reproduce it.

**Closed by peace-maker** 2018-02-28 15:36 UTC
