### ISSUE TITLE
[BUG] Levels not saved when upgrade/downgrade

### ISSUE THREAD

**Issue by paulocrash** [peace-maker/smrpg#293] opened 2018-08-28 00:46 UTC
The levels of powers do not save when we make changes to them.

Example, if I'm with speed at level 3 and I jump at level 2, and it sells a speed level to buy the leap I get normal.

Then I get the speed in level 2 and I jump in level 3, but if I give retry on the server, or I disconnect and when I come back, the level buga.

In case the speed that was in level 2, continues with 2 and the jump that was 3 drops to 2, and I no longer have the credits to buy it back.

It's as if the plugin does not save the changes.

What could it be? Would it be correct?

**Log errors: [errors_20180903.log](https://github.com/peace-maker/smrpg/files/2346622/errors_20180903.log)**

**Useful Information:**
**SourceMod:**  1.9 - build 6248
**Metamod:** 1.10 - build 966
**SM:RPG:** smrpg-rev532.tar.gz - 2018-08-16 18:14
**MySQL Database:**  5.6.40 - MySQL Community Server (GPL)

##### **_Sorry for my bad English, if you do not understand let me know that I try to explain better._**

**Comment by peace-maker** [comment] 2018-09-11 13:37
This is a duplicate of your other issue in #294.

**Closed by peace-maker** 2018-09-11 13:37 UTC
