### ISSUE TITLE
Some problems with SMRPG Effects.

### ISSUE THREAD

**Issue by COSMOS-USA** [peace-maker/smrpg#309] opened 2018-12-25 06:30 UTC
Hello guys!
I have some problems with SMRPG Effects.
This plugin always spamming errors to console, i saw past topics but it's can't help me, i changed files in gamedata but it didn't work.

Exm. errors:

L 12/25/2018 - 09:04:23: [SM] Exception reported: Handle 20b2070e is invalid (error 1)
L 12/25/2018 - 09:04:23: [SM] Blaming: smrpg_effects.smx
L 12/25/2018 - 09:04:23: [SM] Call stack trace:
L 12/25/2018 - 09:04:23: [SM]   [0] CloseHandle
L 12/25/2018 - 09:04:23: [SM]   [1] Line 248, /home/travis/build/peace-maker/smrpg/build/addons/sourcemod/scripting/include/smlib/general.inc::ClearHandle
L 12/25/2018 - 09:04:23: [SM]   [2] Line 39, smrpg_effects/ignite.sp::ResetIgniteClient
L 12/25/2018 - 09:04:23: [SM]   [3] Line 95, smrpg_effects.sp::Event_OnPlayerSpawn

 I hope that you will help me. Thank you!

**Comment by peace-maker** [comment] 2019-01-05 14:05
Duplicate of #302 - this one has a different stack trace though, but most likely caused by the same problem.

**Closed by peace-maker** 2019-01-05 14:05 UTC
