### ISSUE TITLE
Denial and weapons

### ISSUE THREAD

**Issue by piotrekkrol7** [peace-maker/smrpg#233] opened 2016-11-28 15:19 UTC
hi i have 1 problem on my surf rpg when i drop my weapon she disappears do you know what can i do and my denial don't work weapon is invisible and when i change weapon she disappears

**Comment by peace-maker** [comment] 2016-11-28 18:45
You probably have another plugin running that strips dropped weapons off the map? There is no code in smrpg that removes weapons.

**Comment by piotrekkrol7** [comment] 2016-11-29 11:09
i don't have another plugin . and i have yet L 11/29/2016 - 12:08:06: [SM] Blaming: smrpg_upgrade_resup.smx
L 11/29/2016 - 12:08:06: [SM] Call stack trace:
L 11/29/2016 - 12:08:06: [SM]   [0] SetFailState
L 11/29/2016 - 12:08:06: [SM]   [1] Line 48, smrpg_upgrade_resup.sp::OnPluginStart
L 11/29/2016 - 12:08:06: [SM] Unable to load plugin "smrpg_upgrade_resup.smx": Error detected in plugin startup (see error logs)

**Comment by peace-maker** [comment] 2016-11-29 18:57
That's a different problem. Please open new issues for different things instead of commenting in another open issue.
The gamedata for CS:GO was updated now.

**Comment by peace-maker** [comment] 2016-12-04 03:00
Duplicate of #225

**Closed by peace-maker** 2016-12-04 03:00 UTC
